---
- hosts: tododb
  become: yes
  tasks: 
    - name: Make sure the Mongod port is open in the firewall
      
      firewalld:
        port: 27017/tcp
        permanent: true
        immediate: yes
        state: enabled
    - name: Provision the Mongod repos file      
      copy:
        src: ./files/mongodb-org-4.4.repo
        dest: /etc/yum.repos.d/mongodb-org-4.4.repo
    - name: Makedure mongo is installed
      
      package:
        name: "{{item}}" 
        state: present
      with_items:
        - tar
        - mongodb-org
    - name: Make sure the service is started
      systemd: 
        name: mongod
        state: started
        enabled: yes
    - name: Download the export file for mongo
      get_url:
        url: https://acit4640.y.vu/docs/module06/resources/mongodb_ACIT4640.tgz
        dest: /tmp/mongod_export.tgz
        username: student
        password: BCIT2020
    - name: Unpack the archive
      unarchive:
        src: /tmp/mongod_export.tgz
        dest: /tmp
        creates: /tmp/ACIT4640
        remote_src: yes
    - name: Make sure data is restored in Mongo
      shell: mongorestore -d ACIT4640 /tmp/ACIT4640
    - name: Make sure mongod listen on all interfaces
      replace:
        path: /etc/mongod.conf
        regexp: 'bindIp: 127.0.0.1'
        replace: 'bindIp: 0.0.0.0'
      register: mongod_conf_task
    - name: Make sure mongo changes are taken into account
      when: mongod_conf_task.changed
      systemd:
        name: mongod
        state: restarted
